### ISSUE TITLE
NOTRO @Noralf Tronnes, pls. can you add functionality to st7735r driver

### ISSUE THREAD

**Issue by rudiratlos** [notro/fbtft#561] opened 2020-08-30 12:21 UTC
Hi Noralf,
since new kernel (5.x) is actve and therefore we've lost functionality of "fbtft_device.c". Which leads to lost support for
adafruit_green display. especially "ADAFRUIT18_GAMMA" and "adafruit18_green_tab_set_addr_win". Is it possible to move these functions/gama-string down to st7735r driver? Gamma-string can be given in a .dts file, but "fbtftops.set_addr_win" can not be redefined in a .dts file. Using native st7735r driver with adafruit_green leed to pixel artefacts on 2 display edges.
I've described that issue here [rpi forum/device tree](https://www.raspberrypi.org/forums/viewtopic.php?f=107&t=281204)
best regards,
SF

**Comment by notro** [comment] 2020-08-31 13:29
Duplicate of #560

**Closed by notro** 2020-08-31 13:29 UTC
